project:
  type: website
  output-dir: docs

website:
  title: "Rigan's Health Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rtytherleigh 
      - icon: linkedin
        href: https://www.linkedin.com/in/rigan-tytherleigh/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

